//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yugioh.Draw.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Components {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Components() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yugioh.Draw.Resources.Components", typeof(Components).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ATKDEF_BAR {
            get {
                object obj = ResourceManager.GetObject("ATKDEF_BAR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ATTRIBUTE__DARK {
            get {
                object obj = ResourceManager.GetObject("ATTRIBUTE__DARK", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ATTRIBUTE__DARKDIVINE {
            get {
                object obj = ResourceManager.GetObject("ATTRIBUTE__DARKDIVINE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ATTRIBUTE__DIVINE {
            get {
                object obj = ResourceManager.GetObject("ATTRIBUTE__DIVINE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ATTRIBUTE__EARTH {
            get {
                object obj = ResourceManager.GetObject("ATTRIBUTE__EARTH", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ATTRIBUTE__FIRE {
            get {
                object obj = ResourceManager.GetObject("ATTRIBUTE__FIRE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ATTRIBUTE__LAUGH {
            get {
                object obj = ResourceManager.GetObject("ATTRIBUTE__LAUGH", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ATTRIBUTE__LIGHT {
            get {
                object obj = ResourceManager.GetObject("ATTRIBUTE__LIGHT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ATTRIBUTE__SPELL {
            get {
                object obj = ResourceManager.GetObject("ATTRIBUTE__SPELL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ATTRIBUTE__START {
            get {
                object obj = ResourceManager.GetObject("ATTRIBUTE__START", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ATTRIBUTE__TRAP {
            get {
                object obj = ResourceManager.GetObject("ATTRIBUTE__TRAP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ATTRIBUTE__TRAPSPELL {
            get {
                object obj = ResourceManager.GetObject("ATTRIBUTE__TRAPSPELL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ATTRIBUTE__WATER {
            get {
                object obj = ResourceManager.GetObject("ATTRIBUTE__WATER", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ATTRIBUTE__WIND {
            get {
                object obj = ResourceManager.GetObject("ATTRIBUTE__WIND", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BACK__DEFAULT {
            get {
                object obj = ResourceManager.GetObject("BACK__DEFAULT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EYE_OF_ANUBIS_HOLOGRAM__GOLD {
            get {
                object obj = ResourceManager.GetObject("EYE_OF_ANUBIS_HOLOGRAM__GOLD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EYE_OF_ANUBIS_HOLOGRAM__SILVER {
            get {
                object obj = ResourceManager.GetObject("EYE_OF_ANUBIS_HOLOGRAM__SILVER", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_DARK_SYNCHRO {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_DARK_SYNCHRO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_EFFECT {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_EFFECT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_EGYPTIAN_GOD_BLUE {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_EGYPTIAN_GOD_BLUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_EGYPTIAN_GOD_RED {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_EGYPTIAN_GOD_RED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_EGYPTIAN_GOD_YELLOW {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_EGYPTIAN_GOD_YELLOW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_FUSION {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_FUSION", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_NORMAL {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_NORMAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_RITUAL {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_RITUAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_SACRED_BEAST_BLUE {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_SACRED_BEAST_BLUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_SACRED_BEAST_RED {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_SACRED_BEAST_RED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_SACRED_BEAST_YELLOW {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_SACRED_BEAST_YELLOW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_SPELL {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_SPELL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_SYNCHRO {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_SYNCHRO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_TOKEN {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_TOKEN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_TRAP {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_TRAP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_WICKED_GOD {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_WICKED_GOD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__ANIME_XYZ {
            get {
                object obj = ResourceManager.GetObject("FRAME__ANIME_XYZ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__DARK_SYNCHRO {
            get {
                object obj = ResourceManager.GetObject("FRAME__DARK_SYNCHRO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__EFFECT {
            get {
                object obj = ResourceManager.GetObject("FRAME__EFFECT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__EGYPTIAN_GOD_BLUE {
            get {
                object obj = ResourceManager.GetObject("FRAME__EGYPTIAN_GOD_BLUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__EGYPTIAN_GOD_RED {
            get {
                object obj = ResourceManager.GetObject("FRAME__EGYPTIAN_GOD_RED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__EGYPTIAN_GOD_YELLOW {
            get {
                object obj = ResourceManager.GetObject("FRAME__EGYPTIAN_GOD_YELLOW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__FUSION {
            get {
                object obj = ResourceManager.GetObject("FRAME__FUSION", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__LEGENDARY_DRAGON {
            get {
                object obj = ResourceManager.GetObject("FRAME__LEGENDARY_DRAGON", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__LINK {
            get {
                object obj = ResourceManager.GetObject("FRAME__LINK", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__NORMAL {
            get {
                object obj = ResourceManager.GetObject("FRAME__NORMAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__PENDULUM_DARK_SYNCHRO {
            get {
                object obj = ResourceManager.GetObject("FRAME__PENDULUM_DARK_SYNCHRO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__PENDULUM_EFFECT {
            get {
                object obj = ResourceManager.GetObject("FRAME__PENDULUM_EFFECT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__PENDULUM_FUSION {
            get {
                object obj = ResourceManager.GetObject("FRAME__PENDULUM_FUSION", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__PENDULUM_NORMAL {
            get {
                object obj = ResourceManager.GetObject("FRAME__PENDULUM_NORMAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__PENDULUM_RITUAL {
            get {
                object obj = ResourceManager.GetObject("FRAME__PENDULUM_RITUAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__PENDULUM_SYNCHRO {
            get {
                object obj = ResourceManager.GetObject("FRAME__PENDULUM_SYNCHRO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__PENDULUM_XYZ {
            get {
                object obj = ResourceManager.GetObject("FRAME__PENDULUM_XYZ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__RITUAL {
            get {
                object obj = ResourceManager.GetObject("FRAME__RITUAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__SACRED_BEAST_BLUE {
            get {
                object obj = ResourceManager.GetObject("FRAME__SACRED_BEAST_BLUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__SACRED_BEAST_RED {
            get {
                object obj = ResourceManager.GetObject("FRAME__SACRED_BEAST_RED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__SACRED_BEAST_YELLOW {
            get {
                object obj = ResourceManager.GetObject("FRAME__SACRED_BEAST_YELLOW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__SPELL {
            get {
                object obj = ResourceManager.GetObject("FRAME__SPELL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__SYNCHRO {
            get {
                object obj = ResourceManager.GetObject("FRAME__SYNCHRO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__TOKEN {
            get {
                object obj = ResourceManager.GetObject("FRAME__TOKEN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__TRAP {
            get {
                object obj = ResourceManager.GetObject("FRAME__TRAP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__WICKED_GOD {
            get {
                object obj = ResourceManager.GetObject("FRAME__WICKED_GOD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FRAME__XYZ {
            get {
                object obj = ResourceManager.GetObject("FRAME__XYZ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LEVEL__NEGATIVE_STAR {
            get {
                object obj = ResourceManager.GetObject("LEVEL__NEGATIVE_STAR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LEVEL__STAR {
            get {
                object obj = ResourceManager.GetObject("LEVEL__STAR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LINK_ARROW__BOTTOM {
            get {
                object obj = ResourceManager.GetObject("LINK_ARROW__BOTTOM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LINK_ARROW__BOTTOM_LEFT {
            get {
                object obj = ResourceManager.GetObject("LINK_ARROW__BOTTOM_LEFT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LINK_ARROW__BOTTOM_RIGHT {
            get {
                object obj = ResourceManager.GetObject("LINK_ARROW__BOTTOM_RIGHT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LINK_ARROW__LEFT {
            get {
                object obj = ResourceManager.GetObject("LINK_ARROW__LEFT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LINK_ARROW__RIGHT {
            get {
                object obj = ResourceManager.GetObject("LINK_ARROW__RIGHT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LINK_ARROW__TOP {
            get {
                object obj = ResourceManager.GetObject("LINK_ARROW__TOP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LINK_ARROW__TOP_LEFT {
            get {
                object obj = ResourceManager.GetObject("LINK_ARROW__TOP_LEFT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LINK_ARROW__TOP_RIGHT {
            get {
                object obj = ResourceManager.GetObject("LINK_ARROW__TOP_RIGHT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PENDULUM__SCALE_BLUE {
            get {
                object obj = ResourceManager.GetObject("PENDULUM__SCALE_BLUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PENDULUM__SCALE_RED {
            get {
                object obj = ResourceManager.GetObject("PENDULUM__SCALE_RED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PROPERTY__CONTINUOUS {
            get {
                object obj = ResourceManager.GetObject("PROPERTY__CONTINUOUS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PROPERTY__COUNTER {
            get {
                object obj = ResourceManager.GetObject("PROPERTY__COUNTER", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PROPERTY__EQUIP {
            get {
                object obj = ResourceManager.GetObject("PROPERTY__EQUIP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PROPERTY__FIELD {
            get {
                object obj = ResourceManager.GetObject("PROPERTY__FIELD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PROPERTY__NORMAL {
            get {
                object obj = ResourceManager.GetObject("PROPERTY__NORMAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PROPERTY__QUICK_PLAY {
            get {
                object obj = ResourceManager.GetObject("PROPERTY__QUICK_PLAY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PROPERTY__RITUAL {
            get {
                object obj = ResourceManager.GetObject("PROPERTY__RITUAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RANK__STAR {
            get {
                object obj = ResourceManager.GetObject("RANK__STAR", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
