//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yugioh.Draw.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Fonts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fonts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yugioh.Draw.Resources.Fonts", typeof(Fonts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ITC_Stone_Serif_LT {
            get {
                object obj = ResourceManager.GetObject("ITC_Stone_Serif_LT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MatrixBoldSmallCaps {
            get {
                object obj = ResourceManager.GetObject("MatrixBoldSmallCaps", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RoGSanSrfStd_Bd {
            get {
                object obj = ResourceManager.GetObject("RoGSanSrfStd_Bd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Stone_Serif_ITC_Medium {
            get {
                object obj = ResourceManager.GetObject("Stone_Serif_ITC_Medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Stone_Serif_Regular {
            get {
                object obj = ResourceManager.GetObject("Stone_Serif_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Stone_Serif_Semibold {
            get {
                object obj = ResourceManager.GetObject("Stone_Serif_Semibold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Yu_Gi_Oh__ITC_Stone_Serif_LT_Italic {
            get {
                object obj = ResourceManager.GetObject("Yu_Gi_Oh__ITC_Stone_Serif_LT_Italic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Yu_Gi_Oh__ITC_Stone_Serif_Small_Caps_Bold {
            get {
                object obj = ResourceManager.GetObject("Yu_Gi_Oh__ITC_Stone_Serif_Small_Caps_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Yu_Gi_Oh__ITC_Stone_Serif_Small_Caps_Bold_EDITED {
            get {
                object obj = ResourceManager.GetObject("Yu_Gi_Oh__ITC_Stone_Serif_Small_Caps_Bold_EDITED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Yu_Gi_Oh__Matrix_Book {
            get {
                object obj = ResourceManager.GetObject("Yu_Gi_Oh__Matrix_Book", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Yu_Gi_Oh__Matrix_Regular_Small_Caps_1 {
            get {
                object obj = ResourceManager.GetObject("Yu_Gi_Oh__Matrix_Regular_Small_Caps_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Yu_Gi_Oh__Matrix_Regular_Small_Caps_2 {
            get {
                object obj = ResourceManager.GetObject("Yu_Gi_Oh__Matrix_Regular_Small_Caps_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
